---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rds-inst-buf-red-v1alpha1-inst
  failurePolicy: Fail
  name: mvalkey-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rds.inst.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - valkeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-valkey-buf-red-v1alpha1-user
  failurePolicy: Fail
  name: muser-v1alpha1.kb.io
  rules:
  - apiGroups:
    - valkey.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - users
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rds-inst-buf-red-v1alpha1-inst
  failurePolicy: Fail
  name: vvalkey-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rds.inst.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - valkeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-valkey-buf-red-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - valkey.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-valkey-buf-red-v1alpha1-failover
  failurePolicy: Fail
  name: vfailover-v1alpha1.kb.io
  rules:
  - apiGroups:
    - valkey.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - failovers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-valkey-buf-red-v1alpha1-user
  failurePolicy: Fail
  name: vuser-v1alpha1.kb.io
  rules:
  - apiGroups:
    - valkey.buf.red
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
