# permissions for end users to view failovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: failover-viewer-role
rules:
- apiGroups:
  - valkey.buf.red
  resources:
  - failovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valkey.buf.red
  resources:
  - failovers/status
  verbs:
  - get
