# permissions for end users to view valkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: rds-valkey-viewer-role
rules:
- apiGroups:
  - rds.valkey.buf.red
  resources:
  - valkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.valkey.buf.red
  resources:
  - valkeys/status
  verbs:
  - get
