# permissions for end users to edit sentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: sentinel-editor-role
rules:
- apiGroups:
  - valkey.buf.red
  resources:
  - sentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - valkey.buf.red
  resources:
  - sentinels/status
  verbs:
  - get
