apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkey-operator-controller-manager
  namespace: system
