apiVersion: valkey.buf.red/v1alpha1
kind: Failover
metadata:
  name: simple-failover
  namespace: default
spec:
  # Use the latest stable Valkey image
  image: valkey/valkey:8.0-alpine
  
  # Number of Valkey replicas
  replicas: 3
  
  # Resource allocation
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  
  # Embedded Sentinel configuration
  sentinel:
    replicas: 3             # 3 sentinel instances
    quorum: 2               # Majority quorum
    
    # Sentinel monitoring configuration
    monitorConfig:
      down-after-milliseconds: "30000"    # 30s to consider master down
      failover-timeout: "180000"          # 3min failover timeout
      parallel-syncs: "1"                 # Sync 1 replica at a time
    
    # Sentinel resource allocation
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
  
  # Network access
  access:
    serviceType: ClusterIP
  
  # Basic Valkey configuration
  customConfigs:
    maxmemory-policy: "allkeys-lru"