apiVersion: rds.valkey.buf.red/v1alpha1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkey-sample
spec:
  # TODO(user): Add fields here
