apiVersion: v2
name: valkey-operator
description: A Helm chart for deploying the Valkey Operator on Kubernetes
type: application
version: 2.0.1
appVersion: "v2.0.2-rc.202609261604.a60f8b5"
keywords:
  - valkey
  - redis
  - operator
  - kubernetes
home: https://github.com/chideat/valkey-operator
sources:
  - https://github.com/chideat/valkey-operator
maintainers:
  - name: chideat
    url: https://github.com/chideat
icon: https://valkey.io/img/valkey-horizontal-color-logo.svg
