name: release-pipeline

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.ref_name }}

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: GitHub Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: |
          ${{ vars.DOCKER_USERNAME }}/valkey-operator:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository_owner }}/valkey-operator:${{ env.RELEASE_VERSION }}
        platforms: linux/amd64,linux/arm64

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
